General packaging updates for 3.1
  * Update binary package names to libparted2 (etc.).  We can safely drop
    the "debian1" suffix now, as the previous incarnation of libparted2 was
    about 14 years ago, and the Conflicts against it were made versioned
    four years ago in 2.2-4.
  * Split off separate packages for libparted-fs-resize, which has a
    different SONAME.
  * Remove largely-unhelpful version from libparted-i18n and libparted-dev
    package names.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -31,25 +31,28 @@ DEBPKGVER = $(shell dpkg-parsechangelog | sed -n -e '/^Version: /{s///;p;q;}')
 
 # The first version of the package to build with the current LIBSONAME
 # This should be changed to the current version when LIBSONAME is changed ...
-DEPVER = 2.2-1
+DEPVER = 3.1-1~
 
 # This is the library's soname. The build will fail if this is wrong, since
 # if the soname has changed we need to update stuff ...
-LIBSONAME = 0
+LIBSONAME = 2
+
+# This is the soname for libparted-fs-resize.
+LIBRESIZESONAME = 0
 
 # The list of sed substitutions we need to do when generating files ...
 # if you put `x' in here somewhere, the substitution `s/@x@/$(x)/'
 # will be done ...
-SUBSTS = BINPKGVER DEPVER LIBSONAME DEB_HOST_MULTIARCH
+SUBSTS = BINPKGVER DEPVER LIBSONAME LIBRESIZESONAME DEB_HOST_MULTIARCH
 
 # Files which are generated by this script ...
 # You will probably need to change this depending on what files your package
 # needs ...
 GENFILES = debian/control \
-	debian/libparted$(LIBSONAME)debian1.files \
-	debian/libparted$(LIBSONAME)debian1.lintian-overrides \
-	debian/libparted$(LIBSONAME)-dev.files \
-	debian/libparted$(LIBSONAME)-i18n.files \
+	debian/libparted$(LIBSONAME).files \
+	debian/libparted$(LIBSONAME)-udeb.files \
+	debian/libparted-fs-resize$(LIBRESIZESONAME).files \
+	debian/libparted-fs-resize$(LIBRESIZESONAME)-udeb.files
 
 ifneq (, $(BINPKGVER))
 GENFILES += debian/parted$(BINPKGVER).files \
@@ -140,11 +143,10 @@ SUBSTLIST = $(foreach subst, $(SUBSTS), s/@$(subst)@/$($(subst))/g;)
 debian/%: debian/%.in debian/rules
 	sed -e '$(SUBSTLIST)' < $< > $@
 
-# This puts the libparted-* packaging files in their right places
-debian/libparted$(LIBSONAME)debian1.%: debian/libparted.%
+debian/libparted$(LIBSONAME)%: debian/libparted%
 	cp $< $@
 
-debian/libparted$(LIBSONAME)%: debian/libparted%
+debian/libparted-fs-resize$(LIBRESIZESONAME)%: debian/libparted-fs-resize%
 	cp $< $@
 
 debian/parted$(BINPKGVER)%: debian/parted%
@@ -162,6 +164,7 @@ echo-vars:
 	@echo "DEB_BUILD_GNU_TYPE: $(DEB_BUILD_GNU_TYPE)"
 	@echo "DEB_HOST_GNU_TYPE: $(DEB_HOST_GNU_TYPE)"
 	@echo "LIBSONAME:	$(LIBSONAME)"
+	@echo "LIBRESIZESONAME:	$(LIBRESIZESONAME)"
 	@echo "BINPKGVER:	$(BINPKGVER)"
 	@echo "GENFILES:	$(GENFILES)"
 	@echo "SUBSTLIST:	$(SUBSTLIST)"
@@ -242,11 +245,12 @@ clean: packaging-files
 	rm -rf build build-deb build-udeb
 
 #	 Remove all debian/libparted*.* except for libparted.*,
-#	 libparted-dev.*, and libparted-i18n.*
+#	 libparted-dev.*, libparted-fs-resize.*, libparted-fs-resize-udeb.*,
+#	 libparted-i18n.*, and libparted-udeb.*
 	@for file in debian/libparted*; do \
 	   file="`basename $$file`"; \
 	   case "$$file" in \
-	   libparted.*|libparted-dev.*|libparted-i18n.*) \
+	   libparted.*|libparted-dev.*|libparted-fs-resize.*|libparted-fs-resize-udeb.*|libparted-i18n.*|libparted-udeb.*) \
 	      ;; \
 	   *) \
 	      echo "rm -rf \"debian/$$file\""; \
@@ -261,7 +265,7 @@ clean: packaging-files
 install: install-deb install-udeb
 	touch $@
 
-install-deb: DH_OPTIONS=-Nparted$(BINPKGVER)-udeb -Nlibparted$(LIBSONAME)-udeb
+install-deb: DH_OPTIONS=-Nparted$(BINPKGVER)-udeb -Nlibparted$(LIBSONAME)-udeb -Nlibparted-fs-resize$(LIBRESIZESONAME)-udeb
 install-deb: build-deb packaging-files
 	dh_testdir
 	dh_testroot
@@ -271,9 +275,10 @@ install-deb: build-deb packaging-files
 	$(MAKE) -C build-deb install DESTDIR=$(CURDIR)/debian/tmp
 
 #	 We need to do 2 things here:
-#	   1. Check that $(LIBSONAME) is actually what the library's SONAME is
-#	   2. Fix the libparted.so symlink to point to
-#	      /lib/$(DEB_HOST_MULTIARCH)/libparted.so.x.x.x rather than
+#	   1. Check that $(LIBSONAME) and $(LIBRESIZESONAME) are actually
+#	      what the libraries' SONAMEs are
+#	   2. Fix the libparted*.so symlinks to point to
+#	      /lib/$(DEB_HOST_MULTIARCH)/libparted*.so.x.x.x rather than
 #	      being relative & pointing to the current directory
 	@(cd debian/tmp/usr/lib; \
 	  SONAME=`ls libparted.so.$(LIBSONAME).*.* | \
@@ -290,8 +295,21 @@ install-deb: build-deb packaging-files
 	     echo " *** package that you are building." >&2; \
 	     exit 1; \
 	  fi; \
+	  RESIZESONAME=`ls libparted-fs-resize.so.$(LIBRESIZESONAME).*.* | \
+	          sed -e 's/^.*\.so\.\([0-9]\+\)\..*$$/\1/'`; \
+	  if [ "$(LIBRESIZESONAME)" -ne "$$RESIZESONAME" ]; then \
+	     echo " *** error: debian/rules thinks that libparted-fs-resize " \
+	          "is version $(LIBRESIZESONAME)" >&2; \
+	     echo " *** library is actually version $$RESIZESONAME. These " \
+	          "should be the same." >&2; \
+	     echo " *** Change the value of LIBRESIZESONAME to " \
+	          "$$RESIZESONAME in debian/rules." >&2; \
+	     exit 1; \
+	  fi; \
 	  ln -sf /lib/$(DEB_HOST_MULTIARCH)/`readlink libparted.so` \
-	         libparted.so)
+	         libparted.so; \
+	  ln -sf /lib/$(DEB_HOST_MULTIARCH)/`readlink libparted-fs-resize.so` \
+	         libparted-fs-resize.so)
 
 	exit
 #	 Make sure the shared libs are in /lib (otherwise there's no point
@@ -313,25 +331,21 @@ install-deb: build-deb packaging-files
 	 fi
 	touch $@
 
-install-udeb: DH_OPTIONS=-pparted$(BINPKGVER)-udeb -plibparted$(LIBSONAME)-udeb
+install-udeb: DH_OPTIONS=-pparted$(BINPKGVER)-udeb -plibparted$(LIBSONAME)-udeb -plibparted-fs-resize$(LIBRESIZESONAME)-udeb
 install-udeb: LIBPARTED_UDEB=$(shell dh_listpackages | grep -E '^libparted$(LIBSONAME)-udeb$$')
+install-udeb: LIBPARTED_FS_RESIZE_UDEB=$(shell dh_listpackages | grep -E '^libparted-fs-resize$(LIBRESIZESONAME)-udeb$$')
 install-udeb: PARTED_UDEB=$(shell dh_listpackages | grep -E '^parted$(BINPKGVER)-udeb$$')
-install-udeb: build-udeb
+install-udeb: build-udeb packaging-files
 	dh_testdir
 	dh_testroot
 	dh_prep
 	dh_installdirs
 
-	[ -z "$(LIBPARTED_UDEB)" ] || \
-	   $(MAKE) -C build-udeb/libparted install \
-			DESTDIR=$(CURDIR)/debian/libparted$(LIBSONAME)-udeb
+	$(MAKE) -C build-udeb/libparted install DESTDIR=$(CURDIR)/debian/tmp-udeb
+	$(MAKE) -C build-udeb/parted install DESTDIR=$(CURDIR)/debian/tmp-udeb
 
-	[ -z "$(LIBPARTED_UDEB)" ] || \
-	   rm -f debian/libparted$(LIBSONAME)-udeb/lib/libparted.so \
-	         debian/libparted$(LIBSONAME)-udeb/lib/libparted.la
+	dh_movefiles --sourcedir=debian/tmp-udeb
 
-	[ -z "$(PARTED_UDEB)" ] || $(MAKE) -C build-udeb/parted install \
-			DESTDIR=$(CURDIR)/debian/parted$(BINPKGVER)-udeb
 	touch $@
 
 # Build architecture-independent packages.
@@ -370,16 +384,20 @@ binary-arch: build install
 	dh_installman
 	dh_installinfo
 	dh_lintian
-	dh_strip -plibparted$(LIBSONAME)debian1 \
-		--dbg-package=libparted$(LIBSONAME)debian1-dbg
-	dh_strip -Nlibparted$(LIBSONAME)debian1
+	DH_OPTIONS= dh_strip -plibparted$(LIBSONAME) \
+		--dbg-package=libparted$(LIBSONAME)-dbg
+	DH_OPTIONS= dh_strip -plibparted-fs-resize$(LIBRESIZESONAME) \
+		--dbg-package=libparted-fs-resize$(LIBRESIZESONAME)-dbg
+	DH_OPTIONS= dh_strip -Nlibparted$(LIBSONAME) -Nlibparted-fs-resize$(LIBRESIZESONAME)
 	dh_link
 	dh_compress
 	dh_fixperms
-	dh_makeshlibs -V'libparted$(LIBSONAME)debian1 (>= $(DEPVER))' \
+	DH_OPTIONS= dh_makeshlibs -plibparted$(LIBSONAME) \
+		-V'libparted$(LIBSONAME) (>= $(DEPVER))' \
 		--add-udeb=$(shell dh_listpackages | grep -E '^libparted$(LIBSONAME)-udeb$$')
-	dh_shlibdeps -Llibparted$(LIBSONAME)debian1 \
-		-l/debian/libparted$(LIBSONAME)debian1/lib
+	DH_OPTIONS= dh_makeshlibs -plibparted-fs-resize$(LIBRESIZESONAME) \
+		--add-udeb=$(shell dh_listpackages | grep -E '^libparted-fs-resize$(LIBRESIZESONAME)-udeb$$')
+	dh_shlibdeps
 	dh_installdeb
 	dh_gencontrol
 	dh_md5sums
